#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --assume-extension --url-ignore /^https*://(localhost:3000|github.com/DartmouthDSC/hydra-conf)/
